# Generated by Django 4.0 on 2022-03-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_num', models.IntegerField(verbose_name='Первое число')),
                ('secont_num', models.IntegerField(verbose_name='Второе число')),
                ('res_multiply', models.IntegerField(verbose_name='Результат умножения')),
            ],
            options={
                'verbose_name': 'число',
                'verbose_name_plural': 'Числа',
            },
        ),
    ]
