# Generated by Django 4.0 on 2022-03-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_numbers_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nums', to='main.category'),
        ),
    ]
