# Generated by Django 4.0.2 on 2022-03-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='photo_link',
            field=models.CharField(default='', max_length=255, verbose_name='Ссылка на фото'),
            preserve_default=False,
        ),
    ]
