# Generated by Django 4.0.2 on 2022-03-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_phone_photo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='memory',
            field=models.PositiveIntegerField(default=0, verbose_name='Объём памяти'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
