# Generated by Django 4.0 on 2022-03-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Triangle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_side', models.IntegerField(verbose_name='Первая строна')),
                ('second_side', models.IntegerField(verbose_name='Вторая строна')),
                ('third_side', models.IntegerField(verbose_name='Третья строна')),
                ('area', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Площадь')),
            ],
            options={
                'verbose_name': 'Стороны',
            },
        ),
    ]
