# Generated by Django 4.0.2 on 2022-03-05 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название команды')),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя игрока')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('photo', models.CharField(blank=True, max_length=255, verbose_name='Фото')),
                ('wiki_link', models.CharField(max_length=255, verbose_name='Ссылка на Википедию')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team', verbose_name='players')),
            ],
            options={
                'verbose_name': 'игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['-pk'],
            },
        ),
    ]
